#!/bin/sh /etc/rc.common

USE_PROCD=1
START=51

NAME=radius4wifi
PROG=/usr/sbin/radiusd

start_service() {
    mkdir -p /var/log /var/run /var/db/radacct /tmp/radiusd

    procd_open_instance
    procd_set_param command $PROG -s -d /etc/radius4wifi
    procd_set_param env LD_LIBRARY_PATH=/usr/lib/freeradius3
    procd_set_param respawn
    procd_close_instance
}