#!/bin/sh

mkdir -p /etc/radius4wifi/certs/pki /var/run/radius4wifi /var/log/radius4wifi

# Migrate legacy 'client_ip' option to 'client_net' list
OLD_IP=$(uci -q get radius4wifi.main.client_ip)
if [ -n "$OLD_IP" ]; then
    uci -q del radius4wifi.main.client_ip
    uci -q add_list radius4wifi.main.client_net="$OLD_IP"
    uci -q commit radius4wifi
fi

# Set default AP IP if no entries exist
if ! uci -q get radius4wifi.main.client_net >/dev/null; then
    uci -q add_list radius4wifi.main.client_net='192.168.1.2'
    uci -q commit radius4wifi
fi

# Only generate a new secret if no secret is set
EXISTING_SECRET=$(uci -q get radius4wifi.main.secret)
if [ -z "$EXISTING_SECRET" ]; then
    RAND_SECRET=$(head -c 100 /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 24)
    uci -q set radius4wifi.main.secret="$RAND_SECRET"
    uci -q commit radius4wifi
fi

/etc/init.d/radius4wifi enable
/etc/init.d/radius4wifi start

exit 0