prefix = /usr
exec_prefix = ${prefix}
sysconfdir = /etc
localstatedir = /var
raddbdir = ${sysconfdir}/radius4wifi

name = radius4wifi
confdir = ${raddbdir}
certdir = ${confdir}/certs

log {
    destination = stdout
    auth = yes
}

modules {
    $INCLUDE mods-enabled/
}

$INCLUDE clients.conf
$INCLUDE sites-enabled/