$INCLUDE vars.conf

prefix = /usr
exec_prefix = /usr
sysconfdir = /etc
localstatedir = /var
sbindir = ${exec_prefix}/sbin
logdir = /var/log/radius4wifi
raddbdir = /etc/radius4wifi

name = radiusd
confdir = ${raddbdir}
certdir = ${confdir}/certs/pki
cadir   = ${confdir}/certs/pki
run_dir = /var/run/radius4wifi
pidfile = ${run_dir}/radiusd.pid

correct_escapes = true
max_request_time = 30
cleanup_delay = 5
max_requests = 1024

log {
    destination = files
    file = ${logdir}/radius.log
    syslog_facility = daemon
    stripped_names = no
    auth = yes
    auth_badpass = yes
    auth_goodpass = no
}

security {
    allow_core_dumps = no
    max_attributes = 200
    reject_delay = 1
    status_server = no
}

modules {
    eap {
        default_eap_type = tls
        timer_expire = 60
        ignore_unknown_eap_types = no

        tls-config conf-tls {
            private_key_file = ${certdir}/server.key
            certificate_file = ${certdir}/server.crt
            ca_file = ${cadir}/ca.crt
            ca_path = ${cadir}
            
            cipher_list = "DEFAULT"
            ecdh_curve = "prime256v1"
            tls_min_version = "1.2"
            
            cache {
                enable = no
            }

            verify {
                tmpdir = /var/run/radius4wifi
            }
        }

        tls {
            tls = conf-tls
            fragment_size = 1024
        }
    }
}

instantiate {
    eap
}

$INCLUDE clients.conf

server default {
    listen {
        type = auth
        ipaddr = *
        port = ${listen_port}
        limit {
            max_connections = 16
            lifetime = 0
            idle_timeout = 30
        }
    }

    authorize {
        eap {
            ok = return
        }
    }

    authenticate {
        eap
    }
}
